import api from './client.js';

export const apiClient = {
    events: (params = {}) => api.get('/event/list', { params }),
    event: (id) => api.get(`/event/details/${id}`),
    eventById: (id) => api.get(`/event/${id}`),
    relatedEvents: (id) => api.get(`/event/${id}/related`),
    categories: () => api.get('/getCategories'),
    cities: (country) => api.get(`/getCities/${encodeURIComponent(country)}`),
    countries: (params = {}) => api.get('/getCountryList', { params }),
    cityCounts: (params = {}) => api.get('/event/city-counts', { params }),
    eventsByType: (params = {}) => api.get('/event/list-by-type', { params }),
    login: (payload) => api.post('/auth/login', payload),
    register: (payload) => api.post('/auth/register', payload),
    becomeOrganizer: () => api.post('/auth/become-organizer'),
    me: () => api.get('/auth/me'),
    orders: () => api.get('/orders'),
    tickets: () => api.get('/orders/tickets'),
    createOrder: (payload) => api.post('/orders', payload),
    createIntent: (orderId) => api.post(`/payments/${orderId}/intent`),
    completeDemo: (orderId) => api.post(`/payments/${orderId}/complete-demo`),
    managerDashboard: (range = 'week') => api.get('/manager/dashboard/home', { params: { range } }),
    managerEvents: () => api.get('/manager/events'),
    managerEvent: (eventId) => api.get(`/manager/events/${eventId}`),
    managerSalesOverview: (eventId) => api.get(`/manager/ticket-orders/sales-overview/${eventId}`),
    managerOrders: (eventId, params = {}) => api.get(`/manager/ticket-orders/get-by-event/${eventId}`, { params }),
    managerCoupons: (eventId) => api.get(`/manager/coupons/by-event/${eventId}`),
    managerCreateEvent: (payload) => api.post('/manager/events/create-or-update', payload),
    managerUpdateEvent: (payload) => api.post('/manager/events/create-or-update', payload),
    managerDeleteEvent: (eventId) => api.get(`/manager/events/delete/${eventId}`),
    managerTickets: (eventId, type = 'all') => api.get(`/manager/event-tickets/get-by-event/${eventId}/${type}`),
    managerCreateTicket: (payload) => api.post('/manager/event-tickets/create', payload),
    managerUpdateTicket: (ticketId, payload) => api.post(`/manager/event-tickets/update/${ticketId}`, payload),
    managerDeleteTicket: (ticketId) => api.get(`/manager/event-tickets/delete/${ticketId}`),
    managerCreateCoupon: (payload) => api.post('/manager/coupons/create', payload),
    managerUpdateCoupon: (couponId, payload) => api.post(`/manager/coupons/update/${couponId}`, payload),
    managerDeleteCoupon: (couponId) => api.get(`/manager/coupons/delete/${couponId}`),
    managerGuests: (eventId) => api.get(`/manager/event-guests/get-by-event/${eventId}`),
    managerCreateGuest: (payload) => api.post('/manager/event-guests/create', payload),
    managerUpdateGuest: (guestId, payload) => api.post(`/manager/event-guests/update/${guestId}`, payload),
    managerDeleteGuest: (guestId) => api.get(`/manager/event-guests/delete/${guestId}`),
    managerHandlers: (eventId, type = 'all') => api.get(`/manager/event-handlers/get-by-event/${eventId}/${type}`),
    managerAddHandler: (payload) => api.post('/manager/event-handlers/add', payload),
    managerDeleteHandler: (handlerId) => api.get(`/manager/event-handlers/delete/${handlerId}`),
    managerImages: (eventId) => api.get(`/manager/event-images/get-by-event/${eventId}`),
    managerCreateImage: (payload) => api.post('/manager/event-images/create', payload),
    managerDeleteImage: (imageId) => api.get(`/manager/event-images/delete/${imageId}`),
    managerNotifications: () => api.get('/manager/notifications/list'),
    managerCheckIns: (eventId) => api.get(`/manager/ticket-orders/check-ins/${eventId}`),
    managerPayouts: (eventId) => api.get(`/manager/ticket-orders/payouts/${eventId}`),
    managerPendingEvents: () => api.get('/manager/events/pending-review'),
    managerApproveEvent: (eventId) => api.post(`/manager/events/${eventId}/approve`),
    managerRejectEvent: (eventId) => api.post(`/manager/events/${eventId}/reject`),
    adminOverview: () => api.get('/manager/admin/overview'),
    adminUsers: () => api.get('/manager/admin/users'),
    adminUpdateUserRole: (userId, role) => api.post(`/manager/admin/users/${userId}/role`, { role }),
    adminSetEventStatus: (eventId, status) => api.post(`/manager/admin/events/${eventId}/status`, { status }),
    adminSetEventFeatured: (eventId, featured) => api.post(`/manager/admin/events/${eventId}/feature`, { featured }),
    createEvent: (payload) => api.post('/manager/events/create-or-update', payload),
    scanTicket: (payload) => api.post('/manager/ticket-orders/scan', payload)
};

export default apiClient;
