import { Router } from 'express';
import { requireAuth, requireRole, requireAdmin } from '../middleware/auth.js';
import { wrapControllers } from '../middleware/asyncHandler.js';
import * as managerFns from '../controllers/managerController.js';

const manager = wrapControllers(managerFns);
const router = Router();
router.use(requireAuth, requireRole('organizer', 'admin'));
router.post('/uploads/presign', manager.presign);
router.post('/uploads/image', manager.uploadImage);
router.get('/dashboard/home', manager.dashboardHome);
router.get('/events', manager.listEvents);
router.post('/events/extract-from-images', manager.uploadImage);
router.get('/events/download-qr', manager.uploadImage);
router.get('/events/pending-review', requireAdmin, manager.pendingEvents);
router.get('/admin/overview', requireAdmin, manager.adminOverview);
router.get('/admin/users', requireAdmin, manager.adminUsers);
router.post('/admin/users/:id/role', requireAdmin, manager.adminUpdateUserRole);
router.post('/admin/events/:id/status', requireAdmin, manager.adminSetEventStatus);
router.post('/admin/events/:id/feature', requireAdmin, manager.adminSetEventFeatured);
router.get('/events/:id', manager.singleEvent);
router.post('/events/create-or-update', manager.createOrUpdateEvent);
router.post('/events/:id/approve', requireAdmin, manager.approveEvent);
router.post('/events/:id/reject', requireAdmin, manager.rejectEvent);
router.post('/events/:id/upgrade', manager.upgradeEvent);
router.get('/events/delete/:id', manager.deleteEvent);
router.get('/event-tickets/get-by-event/:id/:type', manager.getTickets);
router.post('/event-tickets/create', manager.createTicket);
router.post('/event-tickets/update/:id', manager.updateTicket);
router.get('/event-tickets/delete/:id', manager.deleteTicket);
router.get('/coupons/by-event/:eventId', manager.coupons);
router.post('/coupons/create', manager.createCoupon);
router.post('/coupons/update/:id', manager.updateCoupon);
router.get('/coupons/delete/:id', manager.deleteCoupon);
router.post('/ticket-orders/sell', manager.sell);
router.get('/ticket-orders/get-by-event/:id', manager.listOrders);
router.get('/ticket-orders/sales-by-type/:id', manager.salesByType);
router.get('/ticket-orders/sales-overview/:id', manager.salesOverview);
router.get('/ticket-orders/payouts/:id', manager.payouts);
router.get('/ticket-orders/check-ins/:id', manager.checkIns);
router.post('/ticket-orders/scan', manager.scanTicket);
router.post('/ticket-orders/:eventId/resend-notification/:ticketOrderId', manager.resendNotification);
router.get('/event-images/get-by-event/:id', manager.images);
router.post('/event-images/create', manager.createImage);
router.get('/event-images/delete/:id', manager.deleteImage);
router.post('/event-images/upload-multiple', manager.createImage);
router.get('/event-guests/get-by-event/:id', manager.guests);
router.post('/event-guests/create', manager.createGuest);
router.post('/event-guests/update/:id', manager.updateGuest);
router.get('/event-guests/delete/:id', manager.deleteGuest);
router.get('/event-handlers/get-by-event/:id/:type', manager.handlers);
router.post('/event-handlers/add', manager.addHandler);
router.post('/event-handlers/update-assigned-tickets', manager.updateAssignedTickets);
router.get('/event-handlers/resend-invite/:id', manager.resendInvite);
router.get('/event-handlers/delete/:id', manager.deleteHandler);
router.post('/event-handlers/accept', manager.acceptHandler);
router.get('/event-handlers/reject/:id', manager.rejectHandler);
router.get('/event-handlers/invitations', manager.handlers);
router.get('/notifications/list', manager.notifications);
router.get('/notifications/settings', manager.notificationSettings);
router.put('/notifications/settings', manager.updateNotificationSettings);
router.get('/event-handler-collections/remittance-due', manager.collections);
router.post('/event-handler-collections/submit-receipts', manager.collections);
router.get('/verified-ambassadors/list', manager.handlers);
router.get('/ticket-outlets/list', manager.handlers);
export default router;
